### ISSUE TITLE
helpq 2022 launch tracker

### ISSUE THREAD

**Issue by q9f** [ethb3rlin/helpq#1]
- [ ] check and fix css everywhere
- [ ] find out how to create users
- [x] enable github login

please comment below if anything else is missing

**Comment by casparschwa** [comment]
When logging in and putting an invalid email, it returns a wrong error message: "wrong password" (should be something like "invalid email").

Overall, it seems that one should be able to loging with the username as well as the email? Right now it only says "email" in the login window. So maybe something like "username or email"

**Comment by casparschwa** [comment]
I would put the home button (currently top left corner) to the top right corner next to the other menu bar items. I couldn't find it for the longest time.
